"""
Verity — Local Q&A Fallback (no API key needed)
===================================================

Answers common question patterns about a batch using only pattern matching
over data the pipeline already generated — no external API call, no cost,
no API key required. This exists so Ask Verity still works end-to-end if
you choose not to set up an Anthropic API key (e.g. for a hackathon demo
where you'd rather not add billing), and as a safety net if the real
Claude call fails for any reason (rate limit, network issue) mid-demo.

It is deliberately narrower than the Claude-powered agent in agent.py:
it can answer questions matching a few concrete patterns (a specific
payment/order ID, category counts, overall match rate, listing a
category's exceptions) but will say plainly when a question doesn't match
anything it knows how to do, rather than guessing. That honesty is the
point — a wrong confident-sounding answer would be worse than an accurate
"I can't answer that without a connected AI model."
"""

import re

CATEGORY_NAMES = {
    "AMOUNT_MISMATCH", "MISSING_IN_LEDGER", "MISSING_IN_SETTLEMENT",
    "DUPLICATE", "DATE_DRIFT", "ID_AMBIGUOUS", "EXACT_MATCH",
}


def _extract_id_mentions(question: str):
    return re.findall(r"(?:pay|order)_[A-Za-z0-9]+", question, flags=re.IGNORECASE)


def _extract_category_mention(question: str):
    q_upper = question.upper().replace(" ", "_")
    for cat in CATEGORY_NAMES:
        if cat in q_upper:
            return cat
    return None


def answer(question: str, summary: dict, exceptions: list) -> dict:
    q_lower = question.lower()

    # Pattern 1: a specific payment/order ID is mentioned — return its
    # explanation directly (already generated by explanations.py).
    mentioned_ids = _extract_id_mentions(question)
    if mentioned_ids:
        matches = [
            e for e in exceptions
            if any(mid.lower() in (str(e.get("payment_id", "")) + str(e.get("order_id", ""))).lower()
                   for mid in mentioned_ids)
        ]
        if matches:
            if len(matches) == 1:
                e = matches[0]
                return {"answer": e["explanation"], "referenced_exception_ids": [e["exception_id"]]}
            lines = [f"- {e['category']}: {e['explanation']}" for e in matches[:5]]
            return {
                "answer": f"Found {len(matches)} matching records:\n" + "\n".join(lines),
                "referenced_exception_ids": [e["exception_id"] for e in matches[:5]],
            }
        return {
            "answer": f"I couldn't find {mentioned_ids[0]} in this batch's exceptions — "
                      f"it may be a clean match (no exception raised) or not part of this batch.",
            "referenced_exception_ids": [],
        }

    # Pattern 2: match rate / overall accuracy questions.
    if any(kw in q_lower for kw in ["match rate", "how accurate", "accuracy", "precision", "recall"]):
        parts = [f"Auto-reconciliation rate is {summary['match_rate']:.1%} ({summary['matched']}/{summary['total_records']} reconciliation units classified as exact matches)."]
        if summary.get("precision") is not None:
            parts.append(f"End-to-end precision: {summary['precision']:.1%}, recall: {summary['recall']:.1%}, F1: {summary['f1']:.1%}.")
        return {"answer": " ".join(parts), "referenced_exception_ids": []}

    # Pattern 3: a specific category mentioned — count + list a few examples.
    category = _extract_category_mention(question)
    if category:
        matching = [e for e in exceptions if e["category"] == category]
        count = summary.get("exceptions_by_category", {}).get(category, len(matching))
        if not matching:
            return {"answer": f"There are no {category} exceptions in this batch.", "referenced_exception_ids": []}
        sample = matching[:3]
        lines = [f"- {e.get('payment_id') or e.get('order_id')}: {e['explanation']}" for e in sample]
        return {
            "answer": f"There are {count} {category} exceptions. Examples:\n" + "\n".join(lines),
            "referenced_exception_ids": [e["exception_id"] for e in sample],
        }

    # Pattern 4: general "what's wrong / most common issues" questions.
    if any(kw in q_lower for kw in ["most common", "biggest issue", "what's wrong", "summary", "overview"]):
        by_cat = summary.get("exceptions_by_category", {})
        if by_cat:
            top = sorted(by_cat.items(), key=lambda x: -x[1])
            lines = [f"- {cat}: {n}" for cat, n in top]
            return {
                "answer": f"Exception breakdown for this batch ({summary['total_records']} reconciliation units):\n"
                          + "\n".join(lines),
                "referenced_exception_ids": [],
            }

    # Nothing matched — say so honestly rather than guess.
    return {
        "answer": (
            "I can answer questions about a specific payment/order ID, match rate and accuracy, "
            "a specific exception category, or a general summary of issues in this batch — but I "
            "couldn't match this question to any of those without a connected AI model. Set "
            "ANTHROPIC_API_KEY to enable full natural-language Q&A for open-ended questions."
        ),
        "referenced_exception_ids": [],
    }
